"""Pydantic v2 domain models for all Kubortex CRDs."""

from .action_execution import (
    ActionDetail,
    ActionExecutionSpec,
    ActionExecutionStatus,
    ApprovalRecord,
    RollbackResult,
    VerificationResult,
)
from .approval import (
    ApprovalActionDetail,
    ApprovalInvestigationContext,
    ApprovalRequestSpec,
    ApprovalRequestStatus,
)
from .autonomy import (
    AutonomyProfileSpec,
    AutonomyProfileStatus,
    AutonomyRule,
    AutonomyScope,
    BlackoutWindow,
    Budgets,
    BudgetUsage,
    ConfidenceThresholds,
    CooldownConfig,
    NamespaceSelector,
    VerificationConfig,
)
from .incident import (
    Condition,
    IncidentSpec,
    IncidentStatus,
    InvestigationSynopsis,
    Signal,
    TargetRef,
    TimelineEntry,
)
from .investigation import (
    DiagnosticHints,
    DiagnosticPathEntry,
    EvidenceItem,
    InvestigationResult,
    InvestigationSpec,
    InvestigationStatus,
    InvestigationTelemetry,
    PriorAttempt,
    RecommendedAction,
    SkillInvocationRecord,
)
from .remediation import (
    ActionProposal,
    PolicyEvaluationResult,
    RemediationPlanSpec,
    RemediationPlanStatus,
    VerificationMetric,
)

__all__ = [
    "ActionDetail",
    "ActionExecutionSpec",
    "ActionExecutionStatus",
    "ActionProposal",
    "ApprovalActionDetail",
    "ApprovalInvestigationContext",
    "ApprovalRecord",
    "ApprovalRequestSpec",
    "ApprovalRequestStatus",
    "AutonomyProfileSpec",
    "AutonomyProfileStatus",
    "AutonomyRule",
    "AutonomyScope",
    "BlackoutWindow",
    "BudgetUsage",
    "Budgets",
    "Condition",
    "ConfidenceThresholds",
    "CooldownConfig",
    "DiagnosticHints",
    "DiagnosticPathEntry",
    "EvidenceItem",
    "IncidentSpec",
    "IncidentStatus",
    "InvestigationResult",
    "InvestigationSpec",
    "InvestigationStatus",
    "InvestigationSynopsis",
    "InvestigationTelemetry",
    "NamespaceSelector",
    "PolicyEvaluationResult",
    "PriorAttempt",
    "RecommendedAction",
    "RemediationPlanSpec",
    "RemediationPlanStatus",
    "RollbackResult",
    "Signal",
    "SkillInvocationRecord",
    "TargetRef",
    "TimelineEntry",
    "VerificationConfig",
    "VerificationMetric",
    "VerificationResult",
]
