{{- if .Values.components.remediator }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubortex-remediator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubortex.componentLabels" (list . "remediator") | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubortex.fullname" . }}-remediator
  labels:
    {{- include "kubortex.componentLabels" (list . "remediator") | nindent 4 }}
rules:
  - apiGroups: [kubortex.io]
    resources: [actionexecutions]
    verbs: [get, list, watch]
  - apiGroups: [kubortex.io]
    resources: [actionexecutions/status]
    verbs: [get, patch, update]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, delete]
  - apiGroups: [""]
    resources: [pods/eviction]
    verbs: [create]
  - apiGroups: [apps]
    resources: [deployments, deployments/scale, statefulsets, statefulsets/scale, replicasets]
    verbs: [get, list, patch, update]
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, list, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubortex.fullname" . }}-remediator
  labels:
    {{- include "kubortex.componentLabels" (list . "remediator") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubortex.fullname" . }}-remediator
subjects:
  - kind: ServiceAccount
    name: kubortex-remediator
    namespace: {{ .Release.Namespace }}
{{- end }}
